---
- import_role:
    name: jdks

- name: Create apps/mvnd
  ansible.builtin.file:
    state: directory
    recurse: true
    path: ~/apps/mvnd

- name: Download mvnd
  ansible.builtin.unarchive:
    src: https://github.com/apache/maven-mvnd/releases/download/1.0-m8/maven-mvnd-1.0-m8-m39-linux-amd64.tar.gz
    dest: ~/apps/mvnd/
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Symlink mvnd
  ansible.builtin.file:
    state: link
    src: ~/apps/mvnd/bin/mvnd
    dest: ~/bin/mvnd

- name: Clone eclipse.jdt.ls
  git:
    repo: https://github.com/eclipse/eclipse.jdt.ls
    dest: ~/dev/eclipse/eclipse.jdt.ls
    depth: 1
    single_branch: true
- name: Build eclipse.jdt.ls
  command: ./mvnw -T1C clean install -Dmaven.test.skip=true -Declipse.jdt.ls.skipGradleChecksums
  environment:
    JAVA_HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}/.m2/jdks/jdk-{{ jdk17 }}"
  args:
    chdir: ~/dev/eclipse/eclipse.jdt.ls

- name: Clone java-debug
  git:
    repo: https://github.com/microsoft/java-debug
    dest: ~/dev/microsoft/java-debug
    depth: 1
    single_branch: true
    version: main
- name: Build java-debug
  command: ./mvnw -T1C clean install -Dmaven.test.skip=true
  environment:
    JAVA_HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}/.m2/jdks/jdk-{{ jdk17 }}"
  args:
    chdir: ~/dev/microsoft/java-debug

- name: Clone vscode-java-test
  git:
    repo: https://github.com/microsoft/vscode-java-test
    dest: ~/dev/microsoft/vscode-java-test
    force: true  # npm commands below modify the package.json
    version: main
    single_branch: true
    depth: 1

- name: Build vscode-java-test
  command: ./mvnw -T1C clean verify -Dmaven.test.skip=true
  environment:
    JAVA_HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}/.m2/jdks/jdk-{{ jdk17 }}"
  args:
    chdir: ~/dev/microsoft/vscode-java-test/java-extension

- name: Create apps folder
  file:
    path: ~/apps/
    state: directory
    mode: 0700

- name: Create async-profiler folder
  file:
    path: ~/apps/async-profiler/
    state: directory
    mode: 0700


- name: Fetch sjk.jar
  get_url:
    url: https://search.maven.org/remotecontent?filepath=org/gridkit/jvmtool/sjk/0.21/sjk-0.21.jar
    dest: ~/apps/sjk.jar

- name: Get and unpack async-profiler
  unarchive:
    src: https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.9/async-profiler-2.9-linux-x64.tar.gz
    dest: ~/apps/async-profiler/
    remote_src: true
    creates: ~/apps/async-profiler/profiler.sh
    extra_opts:
      - --strip-components=1

- name: Get jfr converter
  get_url:
    url: https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.9/converter.jar
    dest: ~/apps/converter.jar


- name: Create jmc folder
  file:
    path: ~/apps/jmc/
    state: directory
    mode: 0700
- name: Get and unpack jmc
  unarchive:
    src: https://github.com/adoptium/jmc-build/releases/download/8.3.0/org.openjdk.jmc-8.3.0-linux.gtk.x86_64.tar.gz
    dest: ~/apps/jmc/
    remote_src: true
    creates: ~/apps/jmc/bin/jmc
    extra_opts:
      - --strip-components=1
- name: Create symlink for jmc
  file:
    src: ~/apps/jmc/jmc
    dest: ~/bin/jmc
    state: link

- name: Clone vscode-java-decompiler
  git:
    repo: https://github.com/dgileadi/vscode-java-decompiler
    dest: ~/dev/dgileadi/vscode-java-decompiler
    single_branch: true
    depth: 1


- name: Create mcs folder
  ansible.builtin.file:
    state: directory
    recurse: true
    path: ~/apps/mcs/

- name: Download mcs
  ansible.builtin.unarchive:
    src: https://github.com/mthmulders/mcs/releases/download/v0.4.1/mcs-0.4.1-linux-x86_64.tar.gz
    dest: ~/apps/mcs/
    remote_src: true
    creates: ~/apps/mcs/bin
    extra_opts:
      - --strip-components=1

- name: Create symlink for mcs
  ansible.builtin.file:
    src: ~/apps/mcs/bin/mcs
    dest: ~/bin/mcs
    state: link

