---
- name: Ensure codelldb folder exists
  file:
    path: ~/apps/codelldb
    state: directory

- name: Download codelldb
  unarchive:
    src: https://github.com/vadimcn/codelldb/releases/download/v1.11.1/codelldb-linux-x64.vsix
    dest: ~/apps/codelldb
    remote_src: true
