---
- name: Install dev packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - base-devel
      - jq
      - ripgrep
      - fd
      - bash-language-server
      - lua-language-server
      - yaml-language-server
      - vscode-json-languageserver
      - vscode-html-languageserver
      - ansible-language-server
      - rust-analyzer
      - zls
      - github-cli
      - luarocks
      - stylua
      - ninja
      - fzf
      - fzy
      - htop
      - delve
      - lldb
      - gulp
      - ruff
      - tidy
      - mergiraf
      - python-docutils  # rst2html is used by vale

- name: Install linters
  become: true
  ansible.builtin.package:
    state: present
    name:
      - codespell
      - shellcheck

- name: Install yay
  aur:
    name: yay-bin

- name: Install tools
  aur:
    name:
      - pgformatter-git
      - stack-static
      - readability-cli
      - vale-bin
      - hadolint-bin
      - comby-bin
      - local-lua-debugger-vscode


- name: Install haskell dev packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - hoogle
      - haskell-ormolu
