---
- name: Gathering facts
  gather_facts:
- name: Install stow
  become: true
  package:
    name: stow
    state: present
- name: Ensure folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config/nvim
    - ~/bin
    - ~/apps
    - ~/.zsh/completion
    - ~/.zsh/plugins
    - ~/.stack
    - ~/.stack/global-project
    - ~/.config/systemd/
    - ~/.luarocks
    - ~/.luarocks/bin
    - ~/.luarocks/lib
    - ~/.luarocks/share
    - ~/.ghc
- name: Ensure ~/.gnupg exists
  file:
    path: ~/.gnupg
    state: directory
    mode: 0700
- name: Create symlinks
  shell: stow bin shell vim intellij sway git alacritty haskell psql gnupg python pinentry lua
  args:
    chdir: ~/dotfiles
- name: Init dircolors
  shell: dircolors -p >! ~/.dircolors
  args:
    executable: /usr/bin/zsh
    creates: ~/.dircolors
