[general]
import = [
  "~/.config/alacritty/light.toml"
]
live_config_reload = true

[font]
size = 12

[font.normal]
family = "NanumGothicCoding"
style = "Regular"

[keyboard]
bindings = [
  {key = "Return", action = "CreateNewWindow", mods = "Control|Shift"},
  {key = "/", action = "SearchForward", mode = "vi|~Search", mods = "Shift"},
  {key = "p", action = "ToggleViMode", mode = "~vi|~Search", mods = "Control|Shift"},
  {key = "p", action = "SearchBackward", mode = "~vi|~Search", mods = "Control|Shift"},
  {key = "p", chars = "↪  |❮ ", mode = "~vi|~Search", mods = "Control|Shift"},
  {key = "p", action = "SearchConfirm", mode = "~vi|~Search", mods = "Control|Shift"},
]

[mouse]
hide_when_typing = false

[scrolling]
history = 100000

[window]
dynamic_title = true
