---
- name: Ensure jdks folder exists
  ansible.builtin.file:
    path: ~/.m2/jdks/
    state: directory
    recurse: true

- name: Install jdks
  ansible.builtin.unarchive:
    src: "https://github.com/adoptium/temurin{{ item.major }}-binaries/releases/download/jdk-{{ item.version }}/OpenJDK{{ item.major }}U-jdk_x64_linux_hotspot_{{ item.version|replace('+', '_') }}.tar.gz"
    dest: ~/.m2/jdks/
    creates: ~/.m2/jdks/jdk-{{ item.version }}
    remote_src: true
  loop:
    - { major: 17, version: "{{ jdk17 }}" }
    - { major: 18, version: "{{ jdk18 }}" }
    - { major: 21, version: "{{ jdk21 }}" }

- name: Install GraalVM Java21
  ansible.builtin.unarchive:
    src: https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.1/graalvm-community-jdk-21.0.1_linux-x64_bin.tar.gz
    dest: ~/.m2/jdks/
    creates: ~/.m2/jdks/graalvm-community-openjdk-21.0.1+12.1/
    remote_src: true
