---
- name: Ensure jdks folder exists
  ansible.builtin.file:
    path: ~/.m2/jdks/
    state: directory
    recurse: true

- name: Install jdks
  ansible.builtin.unarchive:
    src: "https://github.com/adoptium/temurin{{ item.major }}-binaries/releases/download/jdk-{{ item.version }}/OpenJDK{{ item.major }}U-jdk_x64_linux_hotspot_{{ item.version|replace('+', '_') }}.tar.gz"
    dest: ~/.m2/jdks/
    creates: ~/.m2/jdks/jdk-{{ item.version }}
    remote_src: true
  loop:
    - { major: 17, version: "{{ jdks_17 }}" }
    - { major: 21, version: "{{ jdks_21 }}" }
    - { major: 23, version: "{{ jdks_23 }}" }
    - { major: 24, version: "{{ jdks_24 }}" }

- name: Install GraalVM-CE Java23
  ansible.builtin.unarchive:
    src: https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-23.0.2/graalvm-community-jdk-23.0.2_linux-x64_bin.tar.gz
    dest: ~/.m2/jdks/
    creates: ~/.m2/jdks/graalvm-community-openjdk-23.0.2+7.1/
    remote_src: true
