---
- name: Create .virtualenvs folder
  ansible.builtin.file:
    state: directory
    recurse: true
    path: ~/.virtualenvs

- name: Setup neovim virtualenv
  pip:
    state: latest
    name:
      - pynvim
      - neovim-remote
    virtualenv: ~/.virtualenvs/nvim
    virtualenv_command: /usr/bin/python3 -m venv
- name: Symlink neovim remote
  file:
    src: ~/.virtualenvs/nvim/bin/nvr
    dest: ~/bin/nvr
    state: link

- name: Checkout vim plugins
  git:
    repo: https://github.com/{{ item.repo }}
    dest: ~/.config/nvim/pack/plugins/{{ item.folder }}/{{ item.repo | basename }}
    single_branch: true
    depth: 1
    version: "{{ item.version | default('HEAD') }}"
  async: 1000
  poll: 0
  loop:
    - { folder: start, repo: junegunn/vim-easy-align }
    - { folder: start, repo: tpope/vim-fugitive }
    - { folder: start, repo: tpope/vim-rhubarb }
    - { folder: start, repo: AndrewRadev/linediff.vim }
    - { folder: start, repo: hynek/vim-python-pep8-indent }
    - { folder: start, repo: phaazon/hop.nvim }
    - { folder: start, repo: jbyuki/venn.nvim }
    - { folder: start, repo: jbyuki/one-small-step-for-vimkind }
    - { folder: opt, repo: sirtaj/vim-openscad }
    - { folder: start, repo: nvim-treesitter/nvim-treesitter-textobjects, version: main }

- name: Checkout vim dev plugins
  git:
    repo: https://github.com/{{ item }}
    dest: ~/.config/nvim/pack/plugins/start/{{ item | basename }}
    update: false
  async: 1000
  poll: 0
  loop:
    - mfussenegger/nvim-jdtls
    - mfussenegger/nvim-dap
    - mfussenegger/nvim-dap-python
    - mfussenegger/nvim-fzy
    - mfussenegger/nvim-qwahl
    - mfussenegger/nvim-lint
    - mfussenegger/nvim-treehopper
    - mfussenegger/nvim-lsp-compl
    - mfussenegger/nvim-ansible
    - mfussenegger/nvim-overfly
    - mfussenegger/nvim-snippasta
