---
- name: Install sway
  become: true
  ansible.builtin.package:
    state: present
    name:
      - sway
      - swayidle
      - waylock
      - slurp
      - bemenu
      - wl-clipboard
      - xdg-desktop-portal-wlr

- name: Install desktop essentials
  become: true
  ansible.builtin.package:
    state: present
    name:
      - openssh
      - alacritty
      - qutebrowser
      - libnitrokey
      - pass

- name: Install audio packages
  become: true
  ansible.builtin.package:
    name:
      - alsa-utils
      - pipewire-pulse
      - pavucontrol

- name: Install fonts
  become: true
  ansible.builtin.package:
    name:
      - noto-fonts
      - noto-fonts-emoji
      - ttf-roboto
      - ttf-hack

- name: Install more fonts
  become: false
  aur:
    name:
      - ttf-juliamono
      - ttf-b612
      - ttf-nanumgothic_coding

- name: Install i3status-rust
  become: false
  aur:
    name: i3status-rust-git
