---
- name: Install haskell tooling lts21
  command: stack install --resolver lts-21.25 ghcid hlint hoogle dhall dhall-json ormolu
  args:
    chdir: ~/
- name: Clone/pull ghcid
  git:
    repo: https://github.com/{{ item }}
    dest: ~/dev/{{ item }}
  loop:
    - ndmitchell/ghcid

- name: Install haskell-language-server
  aur:
    name: haskell-language-server-static
    state: present

- name: Install ghcid vim plugin
  command: cp -a ~/dev/ndmitchell/ghcid/plugins/nvim ~/.config/nvim/pack/plugins/start/ghcid
