---
- name: Setup tools virtualenv
  pip:
    state: latest
    name:
      - httpie
      - twine
      - shiv
      - wheel
      - vdirsyncer
      - khard
      - yamllint
      - vimg
      - proselint
      - ansible-lint
      - ipython
      - ptpython
      - memory_profiler
      - debugpy
      - exodus-bundler
      - llm
      - pgcli
    virtualenv: ~/.virtualenvs/tools
    virtualenv_command: /usr/bin/python3 -m venv
- name: Symlink tools
  file:
    src: ~/.virtualenvs/tools/bin/{{ item }}
    dest: ~/bin/{{ item }}
    state: link
  loop:
    - http
    - twine
    - shiv
    - vdirsyncer
    - khard
    - yamllint
    - vimg
    - proselint
    - ansible-lint
    - mprof
    - llm
    - pgcli
- name: Symlink py -> ptipython
  file:
    src: ~/.virtualenvs/tools/bin/ptipython
    dest: ~/bin/py
    state: link
